import { css } from '../../utils/cssBuilder';
import { THEME } from '../theme';

export const authorManagerModalStyles = css({
  '#kdl-author-manager-overlay': {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: THEME.colors.overlayBg,
    display: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: THEME.zIndex.modalOverlay,
    WebkitBackdropFilter: 'blur(12px)',
    backdropFilter: 'blur(12px)',
  },
  '#kdl-author-manager-modal': {
    background: THEME.colors.modalBg,
    color: THEME.colors.textMain,
    borderRadius: THEME.borderRadius.modal,
    width: '840px',
    maxWidth: '95vw',
    height: '88vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: THEME.shadows.modal,
    border: `1px solid ${THEME.colors.borderSubtle}`,
    overflow: 'hidden',
  },
  '#kdl-manager-header': {
    padding: '18px 24px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  '#kdl-manager-header h3': {
    margin: 0,
    color: THEME.colors.primary,
    fontSize: '1.25rem',
    fontWeight: '700',
  },
  '#kdl-manager-cache-status': {
    fontSize: '0.8em',
    color: THEME.colors.textMuted,
    marginLeft: '10px',
  },
  '#kdl-manager-controls': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    padding: '12px 24px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
  },
  '#kdl-manager-search': {
    flexGrow: 1,
    padding: '9px 14px',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: `1px solid ${THEME.colors.borderSubtle}`,
    borderRadius: THEME.borderRadius.lg,
    color: THEME.colors.textMain,
    fontSize: '0.88rem',
    transition: 'all 0.2s ease',
  },
  '#kdl-manager-search:focus': {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: THEME.colors.primary,
    outline: 'none',
    boxShadow: '0 0 0 3px rgba(56, 189, 248, 0.2)',
  },
  '.kdl-manager-btn': {
    padding: '9px 16px',
    border: 'none',
    borderRadius: THEME.borderRadius.lg,
    color: '#fff',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.88rem',
    transition: 'all 0.2s ease',
  },
  '.kdl-manager-btn:hover:not(:disabled)': {
    filter: 'brightness(1.15)',
  },
  '.kdl-manager-btn:disabled': {
    opacity: 0.55,
    cursor: 'not-allowed',
  },
  '#kdl-manager-refresh': {
    background: THEME.colors.btnInfoGradient,
  },
  '#kdl-manager-sort': {
    padding: '8px 6px',
    backgroundColor: THEME.colors.inputBg,
    border: `1px solid ${THEME.colors.borderSubtle}`,
  },
  '#kdl-manager-select-all': {
    background: THEME.colors.btnPrimaryGradient,
  },
  '#kdl-manager-deselect-all': {
    background: THEME.colors.btnDangerGradient,
  },
  '#kdl-manager-download': {
    background: THEME.colors.btnSuccessGradient,
  },
  '#kdl-manager-close': {
    background: THEME.colors.btnSecondaryGradient,
  },
  '#kdl-manager-post-list': {
    overflowY: 'auto',
    flexGrow: 1,
    padding: '14px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  '#kdl-manager-post-list .post-item': {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: THEME.borderRadius.lg,
    marginBottom: 0,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backgroundColor: THEME.colors.cardBg,
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  '#kdl-manager-post-list .post-item:hover': {
    backgroundColor: THEME.colors.cardHoverBg,
    borderColor: 'rgba(56, 189, 248, 0.3)',
    transform: 'translateY(-1px)',
  },
  '#kdl-manager-post-list .post-item input[type=checkbox]': {
    marginRight: '15px',
    width: '18px',
    height: '18px',
    accentColor: THEME.colors.primary,
    cursor: 'pointer',
  },
  '.post-item-label': {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  '.post-item-title': {
    fontWeight: '600',
    color: '#f1f5f9',
    fontSize: '0.92rem',
  },
  '.post-item-date': {
    fontSize: '0.8rem',
    color: THEME.colors.textMuted,
  },
  '#kdl-manager-footer': {
    padding: '14px 24px',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    marginTop: 'auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(20, 24, 32, 0.95)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  '.post-item-preview': {
    width: '60px',
    height: '60px',
    objectFit: 'cover',
    marginRight: '15px',
    borderRadius: THEME.borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
  },
  '.post-item-open-link': {
    marginLeft: 'auto',
    padding: '6px 12px',
    fontSize: '1rem',
    lineHeight: 1,
    textDecoration: 'none',
    borderRadius: THEME.borderRadius.md,
    transition: 'all 0.2s ease',
    color: THEME.colors.textMuted,
  },
  '.post-item-open-link:hover': {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: THEME.colors.primary,
  },
});
