import { css } from '../../utils/cssBuilder';
import { THEME } from '../theme';

export const filePickerModalStyles = css({
  '#kdl-file-picker-overlay': {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: THEME.colors.overlayBg,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: THEME.zIndex.modalOverlay,
    WebkitBackdropFilter: 'blur(12px)',
    backdropFilter: 'blur(12px)',
  },
  '#kdl-file-picker-modal': {
    background: THEME.colors.modalBg,
    color: THEME.colors.textMain,
    borderRadius: THEME.borderRadius.modal,
    padding: '24px',
    width: '620px',
    maxWidth: '92vw',
    maxHeight: '82vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: THEME.shadows.modal,
    border: `1px solid ${THEME.colors.borderSubtle}`,
  },
  '#kdl-file-picker-modal h4': {
    margin: '0 0 16px',
    color: THEME.colors.primary,
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    paddingBottom: '12px',
    textAlign: 'center',
    fontSize: '1.2rem',
    fontWeight: '700',
  },
  '#kdl-file-picker-list': {
    overflowY: 'auto',
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  '#kdl-file-picker-list li': {
    margin: 0,
  },
  '#kdl-file-picker-list a': {
    display: 'block',
    padding: '10px 14px',
    backgroundColor: THEME.colors.cardBg,
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: THEME.borderRadius.lg,
    color: THEME.colors.textSubtle,
    textDecoration: 'none',
    transition: 'all 0.2s ease',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    fontSize: '0.88rem',
  },
  '#kdl-file-picker-list a:hover': {
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderColor: THEME.colors.primary,
    color: '#ffffff',
    transform: 'translateX(3px)',
  },
});
