import { css } from '../../utils/cssBuilder';
import { THEME } from '../theme';

export const filePickerModalStyles = css({
  '#kdl-file-picker-overlay': {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(10, 13, 18, 0.82)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: THEME.zIndex.modalOverlay,
    WebkitBackdropFilter: 'blur(12px)',
    backdropFilter: 'blur(12px)',
  },
  '#kdl-file-picker-modal': {
    position: 'relative',
    background: 'linear-gradient(145deg, #1e2229 0%, #12151a 100%)',
    color: '#f8fafc',
    borderRadius: THEME.borderRadius.modal,
    padding: '24px',
    width: '560px',
    maxWidth: '92vw',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.6), 0 0 1px rgba(255, 255, 255, 0.15)',
    border: `1px solid ${THEME.colors.borderSubtle}`,
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  '#kdl-file-picker-modal .kdl-modal-header': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    paddingBottom: '14px',
    marginBottom: '16px',
  },
  '#kdl-file-picker-modal h4': {
    margin: 0,
    color: THEME.colors.primary,
    fontSize: '1.15rem',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  '#kdl-file-picker-modal .kdl-modal-close': {
    background: 'transparent',
    border: 'none',
    color: '#94a3b8',
    fontSize: '1.25rem',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: THEME.borderRadius.md,
    transition: 'color 0.2s, background-color 0.2s',
  },
  '#kdl-file-picker-modal .kdl-modal-close:hover': {
    color: '#ffffff',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  '#kdl-file-picker-list': {
    overflowY: 'auto',
    overflowX: 'hidden',
    listStyle: 'none',
    padding: '4px',
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    maxHeight: '60vh',
  },
  '#kdl-file-picker-list::-webkit-scrollbar, #kdl-multi-file-picker-list::-webkit-scrollbar': {
    width: '6px',
  },
  '#kdl-file-picker-list::-webkit-scrollbar-track, #kdl-multi-file-picker-list::-webkit-scrollbar-track': {
    background: 'rgba(0, 0, 0, 0.2)',
    borderRadius: THEME.borderRadius.sm,
  },
  '#kdl-file-picker-list::-webkit-scrollbar-thumb, #kdl-multi-file-picker-list::-webkit-scrollbar-thumb': {
    background: 'rgba(255, 255, 255, 0.2)',
    borderRadius: THEME.borderRadius.sm,
  },
  '#kdl-file-picker-list::-webkit-scrollbar-thumb:hover, #kdl-multi-file-picker-list::-webkit-scrollbar-thumb:hover': {
    background: 'rgba(255, 255, 255, 0.35)',
  },
  '#kdl-file-picker-list li': {
    margin: 0,
    width: '100%',
    boxSizing: 'border-box',
  },
  '#kdl-file-picker-list a': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 16px',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: THEME.borderRadius.lg,
    color: '#e2e8f0',
    textDecoration: 'none',
    transition: 'all 0.2s ease',
    fontSize: '0.9rem',
    fontWeight: '500',
    wordBreak: 'break-all',
    boxSizing: 'border-box',
    width: '100%',
  },
  '#kdl-file-picker-list a:hover': {
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
    borderColor: 'rgba(56, 189, 248, 0.4)',
    color: '#ffffff',
    transform: 'translateX(3px)',
  },
  '#kdl-file-picker-list .kdl-file-icon': {
    fontSize: '1.1rem',
    flexShrink: 0,
  },
  '#kdl-file-picker-list .kdl-file-name': {
    flexGrow: 1,
  },
  '.kdl-multi-picker-toolbar': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
    paddingBottom: '12px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
  },
  '.kdl-tb-btn': {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    color: '#e2e8f0',
    border: `1px solid ${THEME.colors.borderSubtle}`,
    borderRadius: THEME.borderRadius.md,
    padding: '6px 12px',
    fontSize: '0.84rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  '.kdl-tb-btn:hover': {
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    color: '#ffffff',
  },
  '.kdl-multi-dl-btn': {
    marginLeft: 'auto',
    background: THEME.colors.successGradient,
    color: '#ffffff',
    border: 'none',
    borderRadius: THEME.borderRadius.md,
    padding: '7px 16px',
    fontSize: '0.88rem',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.3)',
    transition: 'all 0.2s ease',
  },
  '.kdl-multi-dl-btn:hover': {
    filter: 'brightness(1.15)',
  },
  '.kdl-multi-dl-btn:disabled': {
    opacity: 0.6,
    cursor: 'not-allowed',
    filter: 'none',
  },
  '#kdl-multi-file-picker-list': {
    overflowY: 'auto',
    maxHeight: '55vh',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    paddingRight: '4px',
  },
  '.kdl-post-group-card': {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: THEME.borderRadius.xl,
    padding: '12px',
  },
  '.kdl-post-group-header': {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
    fontWeight: '600',
    fontSize: '0.92rem',
    color: THEME.colors.primary,
  },
  '.kdl-post-group-date': {
    fontSize: '0.8rem',
    color: '#94a3b8',
    fontWeight: 'normal',
  },
  '.kdl-group-file-list': {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  '.kdl-multi-file-item': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 12px',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: THEME.borderRadius.md,
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    fontSize: '0.88rem',
  },
  '.kdl-multi-file-item:hover': {
    backgroundColor: 'rgba(56, 189, 248, 0.1)',
  },
  '.kdl-multi-file-cb': {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
  },
});
