import { css } from '../../utils/cssBuilder';

/**
 * Isolated Plyr Video Player Styles.
 */
export const kuiPlyrStyles = css({
  '@keyframes plyr-progress': {
    to: {
      backgroundPosition: 'var(--plyr-progress-loading-size, 25px) 0',
    },
  },
  '@keyframes plyr-popup': {
    '0%': { opacity: 0.5, transform: 'translateY(10px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
  },
  '@keyframes plyr-fade-in': {
    '0%': { opacity: 0 },
    to: { opacity: 1 },
  },

  '.plyr': {
    MozOsxFontSmoothing: 'grayscale',
    WebkitFontSmoothing: 'antialiased',
    alignItems: 'center',
    direction: 'ltr',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'var(--plyr-font-family, inherit)',
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 'var(--plyr-font-weight-regular, 400)',
    lineHeight: 'var(--plyr-line-height, 1.7)',
    maxWidth: '100%',
    minWidth: '200px',
    position: 'relative',
    textShadow: 'none',
    transition: 'box-shadow .3s ease',
    zIndex: 0,
  },
  '.plyr audio, .plyr iframe, .plyr video': {
    display: 'block',
    height: '100%',
    width: '100%',
  },
  '.plyr button': {
    font: 'inherit',
    lineHeight: 'inherit',
    width: 'auto',
  },
  '.plyr:focus': {
    outline: 0,
  },
  '.plyr--full-ui': {
    boxSizing: 'border-box',
  },
  '.plyr--full-ui *, .plyr--full-ui :after, .plyr--full-ui :before': {
    boxSizing: 'inherit',
  },
  '.plyr--full-ui a, .plyr--full-ui button, .plyr--full-ui input, .plyr--full-ui label': {
    touchAction: 'manipulation',
  },
  '.plyr__badge': {
    background: 'var(--plyr-badge-background, #4a5464)',
    borderRadius: 'var(--plyr-badge-border-radius, 2px)',
    color: 'var(--plyr-badge-text-color, #fff)',
    fontSize: 'var(--plyr-font-size-badge, 9px)',
    lineHeight: 1,
    padding: '3px 4px',
  },
  '.plyr--full-ui ::-webkit-media-text-track-container': {
    display: 'none',
  },
  '.plyr__captions': {
    animation: 'plyr-fade-in .3s ease',
    bottom: 0,
    display: 'none',
    fontSize: 'var(--plyr-font-size-small, 13px)',
    left: 0,
    padding: 'var(--plyr-control-spacing, 10px)',
    position: 'absolute',
    textAlign: 'center',
    transition: 'transform .4s ease-in-out',
    width: '100%',
  },
  '.plyr__captions span:empty': {
    display: 'none',
  },

  '@media (min-width: 480px)': {
    '.plyr__captions': {
      fontSize: 'var(--plyr-font-size-base, 15px)',
      padding: 'calc(var(--plyr-control-spacing, 10px)*2)',
    },
  },
  '@media (min-width: 768px)': {
    '.plyr__captions': {
      fontSize: 'var(--plyr-font-size-large, 18px)',
    },
  },

  '.plyr--captions-active .plyr__captions': {
    display: 'block',
  },
  '.plyr:not(.plyr--hide-controls) .plyr__controls:not(:empty)~.plyr__captions': {
    transform: 'translateY(calc(var(--plyr-control-spacing, 10px)*-4))',
  },
  '.plyr__caption': {
    background: 'var(--plyr-captions-background, #000c)',
    borderRadius: '2px',
    WebkitBoxDecorationBreak: 'clone',
    boxDecorationBreak: 'clone',
    color: 'var(--plyr-captions-text-color, #fff)',
    lineHeight: '185%',
    padding: '.2em .5em',
    whiteSpace: 'pre-wrap',
  },
  '.plyr__caption div': {
    display: 'inline',
  },
  '.plyr__control': {
    background: '#0000',
    border: 0,
    borderRadius: 'var(--plyr-control-radius, 4px)',
    color: 'inherit',
    cursor: 'pointer',
    flexShrink: 0,
    overflow: 'visible',
    padding: 'calc(var(--plyr-control-spacing, 10px)*.7)',
    position: 'relative',
    transition: 'all .1s ease-in-out',
  },
  '.plyr__control svg': {
    display: 'block',
    fill: 'currentColor',
    height: 'var(--plyr-control-icon-size, 18px)',
    pointerEvents: 'none',
    width: 'var(--plyr-control-icon-size, 18px)',
  },
  '.plyr__control:focus': {
    outline: 0,
  },
  '.plyr__control:focus-visible': {
    outline: '2px dashed var(--plyr-focus-visible-color, var(--plyr-color-main, #00b2ff))',
    outlineOffset: '2px',
  },
  'a.plyr__control': {
    textDecoration: 'none',
  },
  '.plyr__control.plyr__control--pressed .icon--not-pressed, .plyr__control.plyr__control--pressed .label--not-pressed, .plyr__control:not(.plyr__control--pressed) .icon--pressed, .plyr__control:not(.plyr__control--pressed) .label--pressed, a.plyr__control:after, a.plyr__control:before': {
    display: 'none',
  },
  '.plyr--full-ui ::-webkit-media-controls': {
    display: 'none',
  },
  '.plyr__controls': {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'flex-end',
    textAlign: 'center',
  },
  '.plyr__controls .plyr__progress__container': {
    flex: '1',
    minWidth: 0,
  },
  '.plyr__controls .plyr__controls__item': {
    marginLeft: 'calc(var(--plyr-control-spacing, 10px)/4)',
  },
  '.plyr__controls .plyr__controls__item:first-child': {
    marginLeft: 0,
    marginRight: 'auto',
  },
  '.plyr__controls .plyr__controls__item.plyr__progress__container': {
    paddingLeft: 'calc(var(--plyr-control-spacing, 10px)/4)',
  },
  '.plyr__controls .plyr__controls__item.plyr__time': {
    padding: '0 calc(var(--plyr-control-spacing, 10px)/2)',
  },
  '.plyr__controls .plyr__controls__item.plyr__progress__container:first-child, .plyr__controls .plyr__controls__item.plyr__time+.plyr__time, .plyr__controls .plyr__controls__item.plyr__time:first-child': {
    paddingLeft: 0,
  },
  '.plyr [data-plyr=airplay], .plyr [data-plyr=captions], .plyr [data-plyr=fullscreen], .plyr [data-plyr=pip], .plyr__controls:empty': {
    display: 'none',
  },
  '.plyr--airplay-supported [data-plyr=airplay], .plyr--captions-enabled [data-plyr=captions], .plyr--fullscreen-enabled [data-plyr=fullscreen], .plyr--pip-supported [data-plyr=pip]': {
    display: 'inline-block',
  },
  '.plyr__menu': {
    display: 'flex',
    position: 'relative',
  },
  '.plyr__menu .plyr__control svg': {
    transition: 'transform .3s ease',
  },
  '.plyr__menu .plyr__control[aria-expanded=true] svg': {
    transform: 'rotate(90deg)',
  },
  '.plyr__menu .plyr__control[aria-expanded=true] .plyr__tooltip': {
    display: 'none',
  },
  '.plyr__menu__container': {
    animation: 'plyr-popup .2s ease',
    background: 'var(--plyr-menu-background, #ffffffe6)',
    borderRadius: 'var(--plyr-menu-radius, 8px)',
    bottom: '100%',
    boxShadow: 'var(--plyr-menu-shadow, 0 1px 2px #00000026)',
    color: 'var(--plyr-menu-color, #4a5464)',
    fontSize: 'var(--plyr-font-size-base, 15px)',
    marginBottom: '10px',
    position: 'absolute',
    right: '-3px',
    textAlign: 'left',
    whiteSpace: 'nowrap',
    zIndex: 3,
  },
  '.plyr__menu__container>div': {
    overflow: 'hidden',
    transition: 'height .35s cubic-bezier(.4,0,.2,1),width .35s cubic-bezier(.4,0,.2,1)',
  },
  '.plyr__menu__container:after': {
    border: 'var(--plyr-menu-arrow-size, 4px) solid #0000',
    borderTopColor: 'var(--plyr-menu-background, #ffffffe6)',
    content: '""',
    height: 0,
    position: 'absolute',
    right: 'calc(var(--plyr-control-icon-size, 18px)/2 + var(--plyr-control-spacing, 10px)*.7 - var(--plyr-menu-arrow-size, 4px)/2)',
    top: '100%',
    width: 0,
  },
  '.plyr__menu__container [role=menu]': {
    padding: 'calc(var(--plyr-control-spacing, 10px)*.7)',
  },
  '.plyr__menu__container [role=menuitem], .plyr__menu__container [role=menuitemradio]': {
    marginTop: '2px',
  },
  '.plyr__menu__container [role=menuitem]:first-child, .plyr__menu__container [role=menuitemradio]:first-child': {
    marginTop: 0,
  },
  '.plyr__menu__container .plyr__control': {
    alignItems: 'center',
    color: 'var(--plyr-menu-color, #4a5464)',
    display: 'flex',
    fontSize: 'var(--plyr-font-size-menu, var(--plyr-font-size-small, 13px))',
    padding: 'calc(var(--plyr-control-spacing, 10px)*.7/1.5) calc(var(--plyr-control-spacing, 10px)*.7*1.5)',
    userSelect: 'none',
    width: '100%',
  },
  '.plyr__menu__container .plyr__control>span': {
    alignItems: 'inherit',
    display: 'flex',
    width: '100%',
  },
  '.plyr__menu__container .plyr__control:after': {
    border: 'var(--plyr-menu-item-arrow-size, 4px) solid #0000',
    content: '""',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
  },
  '.plyr__menu__container .plyr__control--forward': {
    paddingRight: 'calc(var(--plyr-control-spacing, 10px)*.7*4)',
  },
  '.plyr__menu__container .plyr__control--forward:after': {
    borderLeftColor: 'var(--plyr-menu-arrow-color, #728197)',
    right: 'calc(var(--plyr-control-spacing, 10px)*.7*1.5 - var(--plyr-menu-item-arrow-size, 4px))',
  },
  '.plyr__menu__container .plyr__control--forward:focus-visible:after, .plyr__menu__container .plyr__control--forward:hover:after': {
    borderLeftColor: 'initial',
  },
  '.plyr__menu__container .plyr__control--back': {
    fontWeight: 'var(--plyr-font-weight-regular, 400)',
    margin: 'calc(var(--plyr-control-spacing, 10px)*.7)',
    marginBottom: 'calc(var(--plyr-control-spacing, 10px)*.7/2)',
    paddingLeft: 'calc(var(--plyr-control-spacing, 10px)*.7*4)',
    position: 'relative',
    width: 'calc(100% - var(--plyr-control-spacing, 10px)*.7*2)',
  },
  '.plyr__menu__container .plyr__control--back:after': {
    borderRightColor: 'var(--plyr-menu-arrow-color, #728197)',
    left: 'calc(var(--plyr-control-spacing, 10px)*.7*1.5 - var(--plyr-menu-item-arrow-size, 4px))',
  },
  '.plyr__menu__container .plyr__control--back:before': {
    background: 'var(--plyr-menu-back-border-color, #dcdfe5)',
    boxShadow: '0 1px 0 var(--plyr-menu-back-border-shadow-color, #fff)',
    content: '""',
    height: '1px',
    left: 0,
    marginTop: 'calc(var(--plyr-control-spacing, 10px)*.7/2)',
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: '100%',
  },
  '.plyr__menu__container .plyr__control--back:focus-visible:after, .plyr__menu__container .plyr__control--back:hover:after': {
    borderRightColor: 'initial',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio]': {
    paddingLeft: 'calc(var(--plyr-control-spacing, 10px)*.7)',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio]:after, .plyr__menu__container .plyr__control[role=menuitemradio]:before': {
    borderRadius: '100%',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio]:before': {
    background: '#0000001a',
    content: '""',
    display: 'block',
    flexShrink: 0,
    height: '16px',
    marginRight: 'var(--plyr-control-spacing, 10px)',
    transition: 'all .3s ease',
    width: '16px',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio]:after': {
    background: '#fff',
    border: 0,
    height: '6px',
    left: '12px',
    opacity: 0,
    top: '50%',
    transform: 'translateY(-50%) scale(0)',
    transition: 'transform .3s ease,opacity .3s ease',
    width: '6px',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio][aria-checked=true]:before': {
    background: 'var(--plyr-control-toggle-checked-background, var(--plyr-color-main, #00b2ff))',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio][aria-checked=true]:after': {
    opacity: 1,
    transform: 'translateY(-50%) scale(1)',
  },
  '.plyr__menu__container .plyr__control[role=menuitemradio]:focus-visible:before, .plyr__menu__container .plyr__control[role=menuitemradio]:hover:before': {
    background: '#23282f1a',
  },
  '.plyr__menu__container .plyr__menu__value': {
    alignItems: 'center',
    display: 'flex',
    marginLeft: 'auto',
    marginRight: 'calc(var(--plyr-control-spacing, 10px)*.7*-1 - -2px)',
    overflow: 'hidden',
    paddingLeft: 'calc(var(--plyr-control-spacing, 10px)*.7*3.5)',
    pointerEvents: 'none',
  },
  '.plyr--full-ui input[type=range]': {
    appearance: 'none',
    background: '#0000',
    border: 0,
    borderRadius: 'calc(var(--plyr-range-thumb-height, 13px)*2)',
    color: 'var(--plyr-range-fill-background, var(--plyr-color-main, #00b2ff))',
    display: 'block',
    height: 'calc(var(--plyr-range-thumb-active-shadow-width, 3px)*2 + var(--plyr-range-thumb-height, 13px))',
    margin: 0,
    minWidth: 0,
    padding: 0,
    transition: 'box-shadow .3s ease',
    width: '100%',
  },
  '.plyr--full-ui input[type=range]::-webkit-slider-runnable-track': {
    background: '#0000',
    backgroundImage: 'linear-gradient(to right,currentColor var(--value, 0),#0000 var(--value, 0))',
    border: 0,
    borderRadius: 'calc(var(--plyr-range-track-height, 5px)/2)',
    height: 'var(--plyr-range-track-height, 5px)',
    transition: 'box-shadow .3s ease',
    userSelect: 'none',
  },
  '.plyr--full-ui input[type=range]::-webkit-slider-thumb': {
    appearance: 'none',
    background: 'var(--plyr-range-thumb-background, #fff)',
    border: 0,
    borderRadius: '100%',
    boxShadow: 'var(--plyr-range-thumb-shadow, 0 1px 1px #23282f26, 0 0 0 1px #23282f33)',
    height: 'var(--plyr-range-thumb-height, 13px)',
    marginTop: 'calc((var(--plyr-range-thumb-height, 13px) - var(--plyr-range-track-height, 5px))/2*-1)',
    position: 'relative',
    transition: 'all .2s ease',
    width: 'var(--plyr-range-thumb-height, 13px)',
  },
  '.plyr--full-ui input[type=range]::-moz-range-track': {
    background: '#0000',
    border: 0,
    borderRadius: 'calc(var(--plyr-range-track-height, 5px)/2)',
    height: 'var(--plyr-range-track-height, 5px)',
    transition: 'box-shadow .3s ease',
    userSelect: 'none',
  },
  '.plyr--full-ui input[type=range]::-moz-range-thumb': {
    background: 'var(--plyr-range-thumb-background, #fff)',
    border: 0,
    borderRadius: '100%',
    boxShadow: 'var(--plyr-range-thumb-shadow, 0 1px 1px #23282f26, 0 0 0 1px #23282f33)',
    height: 'var(--plyr-range-thumb-height, 13px)',
    position: 'relative',
    transition: 'all .2s ease',
    width: 'var(--plyr-range-thumb-height, 13px)',
  },
  '.plyr--full-ui input[type=range]::-moz-range-progress': {
    background: 'currentColor',
    borderRadius: 'calc(var(--plyr-range-track-height, 5px)/2)',
    height: 'var(--plyr-range-track-height, 5px)',
  },
  '.plyr--full-ui input[type=range]::-ms-track': {
    color: '#0000',
  },
  '.plyr--full-ui input[type=range]::-ms-fill-upper, .plyr--full-ui input[type=range]::-ms-track': {
    background: '#0000',
    border: 0,
    borderRadius: 'calc(var(--plyr-range-track-height, 5px)/2)',
    height: 'var(--plyr-range-track-height, 5px)',
    transition: 'box-shadow .3s ease',
    userSelect: 'none',
  },
  '.plyr--full-ui input[type=range]::-ms-fill-lower': {
    background: 'currentColor',
    border: 0,
    borderRadius: 'calc(var(--plyr-range-track-height, 5px)/2)',
    height: 'var(--plyr-range-track-height, 5px)',
    transition: 'box-shadow .3s ease',
    userSelect: 'none',
  },
  '.plyr--full-ui input[type=range]::-ms-thumb': {
    background: 'var(--plyr-range-thumb-background, #fff)',
    border: 0,
    borderRadius: '100%',
    boxShadow: 'var(--plyr-range-thumb-shadow, 0 1px 1px #23282f26, 0 0 0 1px #23282f33)',
    height: 'var(--plyr-range-thumb-height, 13px)',
    marginTop: 0,
    position: 'relative',
    transition: 'all .2s ease',
    width: 'var(--plyr-range-thumb-height, 13px)',
  },
  '.plyr--full-ui input[type=range]::-ms-tooltip': {
    display: 'none',
  },
  '.plyr--full-ui input[type=range]::-moz-focus-outer': {
    border: 0,
  },
  '.plyr--full-ui input[type=range]:focus': {
    outline: 0,
  },
  '.plyr--full-ui input[type=range]:focus-visible::-webkit-slider-runnable-track': {
    outline: '2px dashed var(--plyr-focus-visible-color, var(--plyr-color-main, #00b2ff))',
    outlineOffset: '2px',
  },
  '.plyr--full-ui input[type=range]:focus-visible::-moz-range-track': {
    outline: '2px dashed var(--plyr-focus-visible-color, var(--plyr-color-main, #00b2ff))',
    outlineOffset: '2px',
  },
  '.plyr--full-ui input[type=range]:focus-visible::-ms-track': {
    outline: '2px dashed var(--plyr-focus-visible-color, var(--plyr-color-main, #00b2ff))',
    outlineOffset: '2px',
  },
  '.plyr__poster': {
    backgroundColor: 'var(--plyr-video-background, #000)',
    backgroundPosition: '50% 50%',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'contain',
    height: '100%',
    left: 0,
    opacity: 0,
    position: 'absolute',
    top: 0,
    transition: 'opacity .2s ease',
    width: '100%',
    zIndex: 1,
  },
  '.plyr--stopped.plyr__poster-enabled .plyr__poster': {
    opacity: 1,
  },
  '.plyr--youtube.plyr--paused.plyr__poster-enabled:not(.plyr--stopped) .plyr__poster': {
    display: 'none',
  },
  '.plyr__time': {
    fontSize: 'var(--plyr-font-size-time, var(--plyr-font-size-small, 13px))',
  },
  '.plyr__time+.plyr__time:before': {
    content: '"⁄"',
    marginRight: 'var(--plyr-control-spacing, 10px)',
  },
  '.plyr__tooltip': {
    background: 'var(--plyr-tooltip-background, #fff)',
    borderRadius: 'var(--plyr-tooltip-radius, 5px)',
    bottom: '100%',
    boxShadow: 'var(--plyr-tooltip-shadow, 0 1px 2px #00000026)',
    color: 'var(--plyr-tooltip-color, #4a5464)',
    fontSize: 'var(--plyr-font-size-small, 13px)',
    fontWeight: 'var(--plyr-font-weight-regular, 400)',
    left: '50%',
    lineHeight: 1.3,
    marginBottom: 'calc(var(--plyr-control-spacing, 10px)/2*2)',
    opacity: 0,
    padding: 'calc(var(--plyr-control-spacing, 10px)/2) calc(var(--plyr-control-spacing, 10px)/2*1.5)',
    pointerEvents: 'none',
    position: 'absolute',
    transform: 'translate(-50%,10px) scale(.8)',
    transformOrigin: '50% 100%',
    transition: 'transform .2s ease .1s,opacity .2s ease .1s',
    whiteSpace: 'nowrap',
    zIndex: 2,
  },
  '.plyr__tooltip:before': {
    borderLeft: 'var(--plyr-tooltip-arrow-size, 4px) solid #0000',
    borderRight: 'var(--plyr-tooltip-arrow-size, 4px) solid #0000',
    borderTop: 'var(--plyr-tooltip-arrow-size, 4px) solid var(--plyr-tooltip-background, #fff)',
    bottom: 'calc(var(--plyr-tooltip-arrow-size, 4px)*-1)',
    content: '""',
    height: 0,
    left: '50%',
    position: 'absolute',
    transform: 'translate(-50%)',
    width: 0,
    zIndex: 2,
  },
  '.plyr .plyr__control:focus-visible .plyr__tooltip, .plyr .plyr__control:hover .plyr__tooltip, .plyr__tooltip--visible': {
    opacity: 1,
    transform: 'translate(-50%) scale(1)',
  },
  '.plyr .plyr__control:hover .plyr__tooltip': {
    zIndex: 3,
  },
  '.plyr__controls>.plyr__control:first-child .plyr__tooltip, .plyr__controls>.plyr__control:first-child+.plyr__control .plyr__tooltip': {
    left: 0,
    transform: 'translateY(10px) scale(.8)',
    transformOrigin: '0 100%',
  },
  '.plyr__controls>.plyr__control:first-child .plyr__tooltip:before, .plyr__controls>.plyr__control:first-child+.plyr__control .plyr__tooltip:before': {
    left: 'calc(var(--plyr-control-icon-size, 18px)/2 + var(--plyr-control-spacing, 10px)*.7)',
  },
  '.plyr__controls>.plyr__control:last-child .plyr__tooltip': {
    left: 'auto',
    right: 0,
    transform: 'translateY(10px) scale(.8)',
    transformOrigin: '100% 100%',
  },
  '.plyr__controls>.plyr__control:last-child .plyr__tooltip:before': {
    left: 'auto',
    right: 'calc(var(--plyr-control-icon-size, 18px)/2 + var(--plyr-control-spacing, 10px)*.7)',
    transform: 'translate(50%)',
  },
  '.plyr__progress': {
    left: 'calc(var(--plyr-range-thumb-height, 13px)*.5)',
    marginRight: 'var(--plyr-range-thumb-height, 13px)',
    position: 'relative',
  },
  '.plyr__progress input[type=range], .plyr__progress__buffer': {
    marginLeft: 'calc(var(--plyr-range-thumb-height, 13px)*-.5)',
    marginRight: 'calc(var(--plyr-range-thumb-height, 13px)*-.5)',
    width: 'calc(100% + var(--plyr-range-thumb-height, 13px))',
  },
  '.plyr__progress input[type=range]': {
    position: 'relative',
    zIndex: 2,
  },
  '.plyr__progress .plyr__tooltip': {
    left: 0,
    maxWidth: '120px',
    overflowWrap: 'break-word',
  },
  '.plyr__progress__buffer': {
    appearance: 'none',
    background: '#0000',
    border: 0,
    borderRadius: '100px',
    height: 'var(--plyr-range-track-height, 5px)',
    left: 0,
    marginTop: 'calc(var(--plyr-range-track-height, 5px)/2*-1)',
    padding: 0,
    position: 'absolute',
    top: '50%',
  },
  '.plyr__progress__buffer::-webkit-progress-bar': {
    background: '#0000',
  },
  '.plyr__progress__buffer::-webkit-progress-value': {
    background: 'currentColor',
    borderRadius: '100px',
    minWidth: 'var(--plyr-range-track-height, 5px)',
    transition: 'width .2s ease',
  },
  '.plyr__progress__buffer::-moz-progress-bar': {
    background: 'currentColor',
    borderRadius: '100px',
    minWidth: 'var(--plyr-range-track-height, 5px)',
    transition: 'width .2s ease',
  },
  '.plyr--video': {
    overflow: 'hidden',
  },
  '.plyr--video.plyr--menu-open': {
    overflow: 'visible',
  },
  '.plyr__video-wrapper': {
    background: 'var(--plyr-video-background, #000)',
    borderRadius: 'inherit',
    height: '100%',
    margin: 'auto',
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  '.plyr__video-embed, .plyr__video-wrapper--fixed-ratio': {
    aspectRatio: '16/9',
  },
  '.plyr__video-embed iframe, .plyr__video-wrapper--fixed-ratio video': {
    border: 0,
    height: '100%',
    left: 0,
    position: 'absolute',
    top: 0,
    width: '100%',
  },
  '.plyr--video .plyr__controls': {
    background: 'var(--plyr-video-controls-background, linear-gradient(#0000, #000000bf))',
    borderBottomLeftRadius: 'inherit',
    borderBottomRightRadius: 'inherit',
    bottom: 0,
    color: 'var(--plyr-video-control-color, #fff)',
    left: 0,
    padding: 'calc(var(--plyr-control-spacing, 10px)/2)',
    paddingTop: 'calc(var(--plyr-control-spacing, 10px)*2)',
    position: 'absolute',
    right: 0,
    transition: 'opacity .4s ease-in-out, transform .4s ease-in-out',
    zIndex: 3,
  },
  '.plyr--video.plyr--hide-controls .plyr__controls': {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(100%)',
  },
  '.plyr--video .plyr__control:focus-visible, .plyr--video .plyr__control:hover, .plyr--video .plyr__control[aria-expanded=true]': {
    background: 'var(--plyr-video-control-background-hover, var(--plyr-color-main, #00b2ff))',
    color: 'var(--plyr-video-control-color-hover, #fff)',
  },
  '.plyr__control--overlaid': {
    background: 'var(--plyr-video-control-background-hover, var(--plyr-color-main, #00b2ff))',
    border: 0,
    borderRadius: '100%',
    color: 'var(--plyr-video-control-color, #fff)',
    display: 'none',
    left: '50%',
    opacity: 0.9,
    padding: 'calc(var(--plyr-control-spacing, 10px)*1.5)',
    position: 'absolute',
    top: '50%',
    transform: 'translate(-50%,-50%)',
    transition: '.3s',
    zIndex: 2,
  },
  '.plyr__control--overlaid svg': {
    left: '2px',
    position: 'relative',
  },
  '.plyr__control--overlaid:focus, .plyr__control--overlaid:hover': {
    opacity: 1,
  },
  '.plyr--playing .plyr__control--overlaid': {
    opacity: 0,
    visibility: 'hidden',
  },
  '.plyr--full-ui.plyr--video .plyr__control--overlaid': {
    display: 'block',
  },
  '.plyr:fullscreen': {
    background: '#000',
    borderRadius: '0!important',
    height: '100%',
    margin: 0,
    width: '100%',
  },
  '.plyr:fullscreen video': {
    height: '100%',
  },
  '.plyr:fullscreen .plyr__control .icon--exit-fullscreen': {
    display: 'block',
  },
  '.plyr:fullscreen .plyr__control .icon--exit-fullscreen+svg': {
    display: 'none',
  },
  '.plyr:fullscreen.plyr--hide-controls': {
    cursor: 'none',
  },
  '.plyr [hidden]': {
    display: 'none!important',
  },
});
