import { css } from '../../utils/cssBuilder';
import { THEME } from '../theme';

export const postCardStyles = css({
  '.user-card, .post-card': {
    position: 'relative !important',
    containerType: 'inline-size',
  },
  '.post-card .post-card-download-controls': {
    position: 'absolute',
    top: '4px',
    right: '4px',
    display: 'none',
    flexDirection: 'column',
    gap: 'clamp(2px, 1.2cqw, 4px)',
    backgroundColor: 'rgba(20, 23, 28, 0.88)',
    WebkitBackdropFilter: 'blur(8px)',
    backdropFilter: 'blur(8px)',
    padding: 'clamp(2px, 1.5cqw, 5px)',
    borderRadius: '5px',
    zIndex: 10,
    border: '1px solid rgba(255, 255, 255, 0.12)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
    maxWidth: '45%',
    boxSizing: 'border-box',
  },
  '.post-card:hover .post-card-download-controls': {
    display: 'flex',
  },
  '.post-card .post-card-download-controls button': {
    padding: 'clamp(2px, 1.2cqw, 4px) clamp(4px, 2.5cqw, 8px)',
    fontSize: 'clamp(0.62rem, 4.8cqw, 0.76rem)',
    fontWeight: '600',
    minWidth: 'clamp(34px, 18cqw, 58px)',
    margin: 0,
    border: '1px solid rgba(255, 255, 255, 0.12) !important',
    borderRadius: '3px',
    color: '#fff !important',
    cursor: 'pointer',
    textAlign: 'center',
    lineHeight: '1.25',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.25)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  '.post-card .post-card-download-controls button:hover': {
    filter: 'brightness(1.15)',
    transform: 'translateY(-1px)',
    boxShadow: '0 3px 6px rgba(0, 0, 0, 0.35)',
  },
  '.post-card .post-card-download-controls button:active': {
    transform: 'translateY(1px)',
  },
  '.post-card .post-card-dl-zip': {
    background: `${THEME.colors.btnSuccessGradient} !important`,
  },
  '.post-card .post-card-dl-img': {
    background: `${THEME.colors.btnPrimaryGradient} !important`,
  },
  '.post-card .post-card-dl-att': {
    background: `${THEME.colors.btnWarnGradient} !important`,
    color: '#ffffff !important',
  },
  '.post-card .post-card-dl-pick': {
    background: `${THEME.colors.btnInfoGradient} !important`,
  },
  '.post-card .post-card-dl-info': {
    background: `${THEME.colors.btnSecondaryGradient} !important`,
  },
  '.post-card .post-card-download-controls button:disabled, .post__actions button[data-is-downloading=true], .post__actions button[data-is-queued=true]': {
    opacity: '0.6 !important',
    cursor: 'not-allowed !important',
  },
  '.post-card .post-card-download-controls button[data-is-queued=true], .post__actions button[data-is-queued=true]': {
    background: `${THEME.colors.orange} !important`,
  },
  '.post-card .post-card-download-controls button[data-is-downloading=true], .post__actions button[data-is-downloading=true]': {
    background: `${THEME.colors.secondary} !important`,
  },
  '.kdl-post-checkbox': {
    position: 'absolute',
    top: '5px',
    left: '5px',
    zIndex: 11,
    width: 'clamp(14px, 8cqw, 20px)',
    height: 'clamp(14px, 8cqw, 20px)',
    cursor: 'pointer',
    padding: '3px',
    margin: 0,
    backgroundClip: 'content-box',
  },
  '.kdl-quick-fav-btn': {
    position: 'absolute',
    top: '6px',
    right: '6px',
    zIndex: 12,
    background: 'rgba(20, 23, 28, 0.85)',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    color: '#fff',
    borderRadius: THEME.borderRadius.sm,
    width: 'clamp(20px, 12cqw, 28px)',
    height: 'clamp(20px, 12cqw, 28px)',
    fontSize: 'clamp(12px, 8cqw, 16px)',
    lineHeight: 1,
    padding: 0,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform .2s, color .2s, opacity .2s',
    opacity: 0,
    pointerEvents: 'none',
  },
  '.user-card:hover .kdl-quick-fav-btn, .post-card:hover .kdl-quick-fav-btn': {
    opacity: 0.9,
    pointerEvents: 'auto',
  },
  '.kdl-quick-fav-btn:hover': {
    opacity: 1,
    transform: 'scale(1.1)',
  },
  '.kdl-quick-fav-btn.kdl-favorited': {
    color: '#ffeb3b',
  },
  '.kdl-quick-fav-btn:disabled': {
    cursor: 'wait',
    color: '#888',
  },
  '.kdl-post-info-tooltip': {
    position: 'absolute',
    bottom: '100%',
    right: 0,
    backgroundColor: '#1a1a1a',
    color: '#f0f0f0',
    padding: '8px',
    borderRadius: THEME.borderRadius.sm,
    border: `1px solid ${THEME.colors.borderLight}`,
    zIndex: THEME.zIndex.dropdown,
    width: '200px',
    fontSize: '.85em',
    display: 'none',
    pointerEvents: 'none',
    boxShadow: '0 3px 10px #00000080',
  },
});
