import { css } from '../../utils/cssBuilder';
import { THEME } from '../theme';

export const settingsModalStyles = css({
  '#kdl-settings-overlay': {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: THEME.colors.overlayBg,
    display: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: THEME.zIndex.panel,
    WebkitBackdropFilter: 'blur(12px)',
    backdropFilter: 'blur(12px)',
  },
  '#kdl-settings-modal': {
    background: THEME.colors.modalBg,
    color: THEME.colors.textMain,
    borderRadius: THEME.borderRadius.modal,
    boxShadow: THEME.shadows.modal,
    border: `1px solid ${THEME.colors.borderSubtle}`,
    width: '1180px',
    maxWidth: '95vw',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '88vh',
    overflow: 'hidden',
  },
  '#kdl-settings-modal-content': {
    overflowY: 'auto',
    padding: '20px 24px',
  },
  '#kdl-settings-modal-content::-webkit-scrollbar': {
    width: THEME.scrollbars.width,
  },
  '#kdl-settings-modal-content::-webkit-scrollbar-track': {
    background: THEME.scrollbars.trackBg,
    borderRadius: '4px',
  },
  '#kdl-settings-modal-content::-webkit-scrollbar-thumb': {
    background: THEME.scrollbars.thumbBg,
    borderRadius: '4px',
  },
  '#kdl-settings-modal-content::-webkit-scrollbar-thumb:hover': {
    background: THEME.scrollbars.thumbHoverBg,
  },
  '#kdl-settings-modal h2': {
    marginTop: 0,
    marginBottom: '16px',
    paddingBottom: '10px',
    color: THEME.colors.primary,
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    textAlign: 'center',
    fontSize: '1.3rem',
    fontWeight: '700',
    letterSpacing: '-0.01em',
  },
  '.kdl-settings-grid': {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
    alignItems: 'start',
  },
  '@media (max-width: 1100px)': {
    '.kdl-settings-grid': {
      gridTemplateColumns: '1fr 1fr',
    },
  },
  '@media (max-width: 768px)': {
    '.kdl-settings-grid': {
      gridTemplateColumns: '1fr',
    },
  },
  '.kdl-settings-col': {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  '.kdl-settings-card': {
    background: THEME.colors.cardBg,
    border: '1px solid rgba(255, 255, 255, 0.07)',
    borderRadius: THEME.borderRadius.xl,
    padding: '14px 16px',
  },
  '.kdl-settings-card h3': {
    marginTop: '0 !important',
    marginBottom: '12px !important',
    color: `${THEME.colors.textSubtle} !important`,
    fontSize: '0.9rem !important',
    fontWeight: '600 !important',
  },
  '.kdl-settings-card h4': {
    marginTop: '14px !important',
    marginBottom: '8px !important',
    color: `${THEME.colors.textSubtle} !important`,
    fontSize: '0.9rem !important',
    fontWeight: '600 !important',
  },
  '.kdl-setting-item': {
    marginBottom: '12px',
  },
  '#kdl-settings-modal label': {
    display: 'block',
    marginTop: '6px',
    marginBottom: '4px',
    fontWeight: '600',
    fontSize: '0.86rem',
    color: 'var(--colour0-primary, #e2e8f0)',
  },
  '#kdl-settings-modal input[type=checkbox]': {
    marginRight: '8px',
    verticalAlign: 'middle',
    width: '16px',
    height: '16px',
    accentColor: THEME.colors.primary,
    cursor: 'pointer',
  },
  '#kdl-settings-modal input[type=number], #kdl-settings-modal input[type=text], #kdl-settings-modal input[type=password], #kdl-settings-modal select': {
    width: '100%',
    padding: '8px 11px',
    borderRadius: '7px',
    border: `1px solid ${THEME.colors.borderSubtle}`,
    backgroundColor: 'var(--colour1-tertiary, #141617)',
    color: THEME.colors.textMain,
    boxSizing: 'border-box',
    fontSize: '0.85rem',
    transition: 'all 0.2s ease',
  },
  '#kdl-settings-modal input[type=number]:focus, #kdl-settings-modal input[type=text]:focus, #kdl-settings-modal input[type=password]:focus, #kdl-settings-modal select:focus': {
    backgroundColor: 'var(--colour1-secondary, #202324)',
    borderColor: THEME.colors.primary,
    boxShadow: '0 0 0 3px rgba(56, 189, 248, 0.2)',
    outline: 'none',
  },
  '#kdl-settings-modal input[type=number]': {
    width: '90px',
  },
  '#kdl-settings-modal select option': {
    backgroundColor: 'var(--colour1-secondary, #202324)',
    color: THEME.colors.textMain,
  },
  '.kdl-cache-box': {
    background: 'var(--colour1-tertiary, rgba(0, 0, 0, 0.25))',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: THEME.borderRadius.lg,
    padding: '10px 12px',
    marginTop: '10px',
    fontSize: '0.82rem',
    color: THEME.colors.textMuted,
  },
  '.kdl-setting-checkbox-grid': {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '6px 10px',
    marginTop: '6px',
  },
  '.kdl-btn-primary, .kdl-btn-info, .kdl-btn-warn, .kdl-btn-danger, .kdl-btn-success': {
    border: 'none !important',
    borderRadius: `${THEME.borderRadius.md} !important`,
    padding: '7px 12px !important',
    fontWeight: '600 !important',
    fontSize: '0.82rem !important',
    cursor: 'pointer !important',
    transition: 'all 0.2s ease !important',
    color: '#fff !important',
    display: 'inline-flex !important',
    alignItems: 'center !important',
    justifyContent: 'center !important',
  },
  '.kdl-btn-primary': { background: `${THEME.colors.btnPrimaryGradient} !important` },
  '.kdl-btn-info': { background: `${THEME.colors.btnInfoGradient} !important` },
  '.kdl-btn-warn': { background: `${THEME.colors.btnWarnGradient} !important` },
  '.kdl-btn-danger': { background: `${THEME.colors.btnDangerGradient} !important` },
  '.kdl-btn-success': { background: `${THEME.colors.btnSuccessGradient} !important` },
  '.kdl-btn-primary:hover, .kdl-btn-info:hover, .kdl-btn-warn:hover, .kdl-btn-danger:hover, .kdl-btn-success:hover': {
    transform: 'translateY(-1px) !important',
    filter: 'brightness(1.12) !important',
    boxShadow: '0 3px 8px rgba(0,0,0,0.3) !important',
  },
  '.kdl-tooltip-trigger': {
    position: 'relative',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '16px',
    height: '16px',
    fontSize: '0.75rem',
    color: THEME.colors.primary,
    cursor: 'help',
    marginLeft: '4px',
    verticalAlign: 'middle',
  },
  '.kdl-tooltip-trigger:hover::after': {
    content: 'attr(data-tooltip)',
    position: 'absolute',
    bottom: '130%',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'var(--colour1-tertiary, #0f172a)',
    color: 'var(--colour0-primary, #f1f5f9)',
    padding: '8px 12px',
    borderRadius: '7px',
    border: '1px solid var(--submit-colour1-primary, rgba(56, 189, 248, 0.35))',
    fontSize: '0.78rem',
    fontWeight: '400',
    whiteSpace: 'normal',
    width: '230px',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.6)',
    zIndex: 10010,
    pointerEvents: 'none',
    lineHeight: '1.4',
    textAlign: 'left',
  },
  '.kdl-tooltip-trigger:hover::before': {
    content: '""',
    position: 'absolute',
    bottom: '115%',
    left: '50%',
    transform: 'translateX(-50%)',
    borderWidth: '5px',
    borderStyle: 'solid',
    borderColor: 'var(--colour1-tertiary, #0f172a) transparent transparent transparent',
    zIndex: 10011,
    pointerEvents: 'none',
  },
  '.kdl-settings-actions': {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 24px',
    backgroundColor: 'var(--colour1-primary, rgba(20, 24, 32, 0.95))',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    marginTop: 'auto',
    position: 'sticky',
    bottom: 0,
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  '.kdl-settings-config-btns': {
    display: 'flex',
    gap: '8px',
  },
  '.kdl-settings-modal-btns': {
    display: 'flex',
    gap: '10px',
  },
  '#kdl-settings-modal button.kdl-save': {
    background: THEME.colors.successGradient,
    color: '#fff',
    padding: '9px 22px',
    border: 'none',
    borderRadius: THEME.borderRadius.lg,
    cursor: 'pointer',
    marginLeft: '10px',
    fontWeight: '600',
    fontSize: '0.88rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 3px 10px rgba(16, 185, 129, 0.25)',
  },
  '#kdl-settings-modal button.kdl-save:hover': {
    transform: 'translateY(-1px)',
    boxShadow: '0 5px 15px rgba(16, 185, 129, 0.35)',
    filter: 'brightness(1.1)',
  },
  '#kdl-settings-modal button.kdl-close': {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    color: THEME.colors.textSubtle,
    border: `1px solid ${THEME.colors.borderSubtle}`,
    padding: '9px 18px',
    borderRadius: THEME.borderRadius.lg,
    cursor: 'pointer',
    marginLeft: '10px',
    fontWeight: '600',
    fontSize: '0.88rem',
    transition: 'all 0.2s ease',
  },
  '#kdl-settings-modal button.kdl-close:hover': {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    color: '#fff',
    transform: 'translateY(-1px)',
  },
});
