import { DownloaderSettings } from '../types';

export const DEFAULT_PRESET_TEMPLATES = [
  { name: 'Default (Date + Author + Title)', template: '{post_date}_{author_name}_{post_title}_{post_id}/{file_index}_{file_name}' },
  { name: 'Author Folder (Author/Date_Title/File)', template: '{author_name}/{post_date}_{post_title}/{file_name}' },
  { name: 'Flat with Index (Author - Title/Index_File)', template: '{author_name} - {post_title}/{file_index}_{file_name}' },
  { name: 'Service & Author ([Service] Author/Date_Title/Index_File)', template: '[{service}] {author_name}/{post_date}_{post_title}/{file_index}_{file_name}' },
  { name: 'Global Index (Author/GlobalIndex_File)', template: '{author_name}/{global_file_index}_{file_name}' }
];

export const DEFAULT_SETTINGS: DownloaderSettings = {
  savePostTags: true,
  savePostComments: false,
  sessionCookie: '',
  enableAPIFetch: true,
  enableDebugLogging: false,
  savePostContentAsText: true,
  maxConcurrentFileDownloadsInZip: 5,
  maxConcurrentOperations: 1,
  showZipButton: true,
  showImagesButton: true,
  showFilesButton: true,
  showCopyLinksButton: true,
  showShareButton: true,
  showTranslateButton: true,
  showImageTranslateButton: true,
  imageTranslateManga: false,
  imageTranslateErase: 'patch',
  imageTranslateMinPx: 12,
  imageTranslateSharpness: 2,
  imageTranslateReflow: false,
  imageTranslateFitToBox: true,
  imageTranslateLineSpacing: 1.25,
  imageTranslatePersist: true,
  imageTranslateDrawBackground: true,
  imageTranslateHullPadding: 0.45,
  imageTranslateOutline: 1,
  imageTranslateAlign: 'auto',
  imageTranslateVertical: 'auto',
  imageTranslateMangaGrowth: 1.45,
  imageTranslateFont: '',
  translationProvider: 'none',
  translationLanguage: 'russian',
  geminiApiKey: '',
  translationModelName: 'gemini-2.5-flash',
  openaiBaseUrl: 'https://api.openai.com/v1',
  openaiApiKey: '',
  openaiModel: 'gpt-4o-mini',
  deeplApiKey: '',
  deeplApiTier: 'free',
  maxConcurrentIndividualDownloads: 4,
  enableDownloadRetries: true,
  downloadRetryCount: 2,
  downloadRetryDelay: 2000,
  zipFileDownloadTimeout: 300000,
  zipCompressionLevel: 0,
  addMetadataFile: true,
  addHtmlIndexInZip: true,
  fileNameTemplate: '{post_date}_{author_name}_{post_title}_{post_id}/{file_index}_{file_name}',
  bulkDownloadMode: 'single',
  bulkSingleSystemPathTemplate: '{author_name}/[Kemono] {author_name} - {post_count} posts.zip',
  bulkSingleInternalPathTemplate: '{post_date}_{post_title}/{file_index}_{file_name}',
  cacheDurationHours: 24,
  bulkMultipleSystemPathTemplate: '{author_name}/{post_date}_{post_title}.zip',
  savedFileNameTemplates: DEFAULT_PRESET_TEMPLATES,
  ignoredFileExtensions: []
};

export const SUPPORTED_SERVICES = [
  'patreon',
  'fanbox',
  'fantia',
  'boosty',
  'subscribestar',
  'dlsite',
  'gumroad',
  'afdian',
  'candystand',
  'pixiv',
  'onlyfans',
  'fansly',
  'candyfuns',
  'discord'
] as const;
