import { DownloaderSettings } from '../types';

export const DEFAULT_SETTINGS: DownloaderSettings = {
  savePostTags: true,
  savePostComments: false,
  sessionCookie: '',
  enableAPIFetch: true,
  enableDebugLogging: false,
  savePostContentAsText: true,
  maxConcurrentFileDownloadsInZip: 5,
  maxConcurrentOperations: 1,
  showZipButton: true,
  showImagesButton: true,
  showFilesButton: true,
  showCopyLinksButton: true,
  showShareButton: true,
  showTranslateButton: true,
  translationProvider: 'none',
  translationLanguage: 'Russian',
  geminiApiKey: '',
  translationModelName: 'gemini-1.5-flash-latest',
  deeplApiKey: '',
  deeplApiTier: 'free',
  maxConcurrentIndividualDownloads: 4,
  enableDownloadRetries: true,
  downloadRetryCount: 2,
  downloadRetryDelay: 2000,
  zipFileDownloadTimeout: 300000,
  zipCompressionLevel: 0,
  addMetadataFile: true,
  addHtmlIndexInZip: true,
  fileNameTemplate: '{post_date}_{author_name}_{post_title}_{post_id}/{file_index}_{file_name}',
  bulkDownloadMode: 'single',
  bulkSingleSystemPathTemplate: '{author_name}/[Kemono] {author_name} - {post_count} posts.zip',
  bulkSingleInternalPathTemplate: '{post_date}_{post_title}/{file_index}_{file_name}',
  cacheDurationHours: 24,
  bulkMultipleSystemPathTemplate: '{author_name}/{post_date}_{post_title}.zip',
  savedFileNameTemplates: []
};
